/**
 * db-find-junk.ts — READ-ONLY. Find automated-test junk that survived cleanup
 * because it hangs off a kept @peppr.test demo account (e.g. "PUBLIC probe
 * 1784228874721", "Accept Product 1784900232765"). Touches nothing.
 */
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '@prisma/client'
import 'dotenv/config'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

// Patterns that scream "generated by an automated test", not curated demo copy.
const JUNK = /(probe|Accept Product|\b\d{10,}\b|^test|lorem|qa[_-]?test|e2e)/i

async function main() {
  // Group posts by author with a sample caption
  const posts = await prisma.post.findMany({
    select: {
      id: true, caption: true, content: true, isProductPost: true,
      author: { select: { username: true, email: true } },
    },
    orderBy: { created_at: 'desc' },
  })
  const products = await prisma.products.findMany({
    select: {
      id: true, title: true, price: true, status: true,
      seller: { select: { store_name: true, store_slug: true, profile: { select: { email: true } } } },
    },
    orderBy: { created_at: 'desc' },
  })

  const junkPosts = posts.filter((p) => JUNK.test(`${p.caption ?? ''} ${p.content ?? ''}`))
  const junkProducts = products.filter((p) => JUNK.test(p.title))

  console.log(`\nPOSTS: ${posts.length} total, ${junkPosts.length} look like test junk`)
  const byAuthor: Record<string, { junk: number; total: number }> = {}
  for (const p of posts) {
    const k = p.author?.username ?? '—'
    byAuthor[k] ??= { junk: 0, total: 0 }
    byAuthor[k].total++
    if (JUNK.test(`${p.caption ?? ''} ${p.content ?? ''}`)) byAuthor[k].junk++
  }
  console.log('  per author (junk/total):')
  for (const [k, v] of Object.entries(byAuthor).sort((a, b) => b[1].junk - a[1].junk))
    console.log(`    ${k.padEnd(20)} ${v.junk}/${v.total}`)

  console.log('\n  sample junk post captions:')
  for (const p of junkPosts.slice(0, 12))
    console.log(`    [${p.author?.username}] ${JSON.stringify((p.caption ?? p.content ?? '').slice(0, 60))}`)

  console.log(`\nPRODUCTS: ${products.length} total, ${junkProducts.length} look like test junk`)
  const byStore: Record<string, { junk: number; total: number }> = {}
  for (const p of products) {
    const k = p.seller?.store_slug ?? '—'
    byStore[k] ??= { junk: 0, total: 0 }
    byStore[k].total++
    if (JUNK.test(p.title)) byStore[k].junk++
  }
  console.log('  per store (junk/total):')
  for (const [k, v] of Object.entries(byStore).sort((a, b) => b[1].junk - a[1].junk))
    console.log(`    ${k.padEnd(24)} ${v.junk}/${v.total}`)

  console.log('\n  sample junk product titles:')
  for (const p of junkProducts.slice(0, 12))
    console.log(`    [${p.seller?.store_slug}] ${JSON.stringify(p.title.slice(0, 50))}  ₦${p.price}`)
}

main().catch((e) => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
